# Generated by Django 2.2.10 on 2020-02-18 09:09

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('t1', models.BooleanField()),
                ('t2', models.BooleanField()),
                ('t3', models.BooleanField()),
                ('t4', models.BooleanField()),
                ('t5', models.BooleanField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
            ],
        ),
    ]
