# Generated by Django 2.2.10 on 2020-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='switch_status',
            field=models.BooleanField(default=0),
        ),
    ]
