# Generated by Django 2.2.10 on 2020-02-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchapp', '0003_auto_20200219_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
