# Generated by Django 2.2.10 on 2020-02-20 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('switchapp', '0004_switch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 5, 6, 56, 295998, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
