# Generated by Django 2.2.10 on 2020-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchapp', '0005_auto_20200220_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_status',
            field=models.IntegerField(null=True),
        ),
    ]
